// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABwHWmrksdYB1HDaiRD46GUoiFY38KHGY',
    appId: '1:618958872225:web:f20abe0e61c445e377dae0',
    messagingSenderId: '618958872225',
    projectId: 'adhikar-2d604',
    authDomain: 'adhikar-2d604.firebaseapp.com',
    storageBucket: 'adhikar-2d604.appspot.com',
    measurementId: 'G-GJDQLJ87SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0MoRyQbkF62xZZQWAFFjQ6b9Ov4ixhrA',
    appId: '1:618958872225:android:5137044db5ace4de77dae0',
    messagingSenderId: '618958872225',
    projectId: 'adhikar-2d604',
    storageBucket: 'adhikar-2d604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6mPVHGA4ySjv2klvv9yKokd-GSTqsB3A',
    appId: '1:618958872225:ios:269d310e22a7a52777dae0',
    messagingSenderId: '618958872225',
    projectId: 'adhikar-2d604',
    storageBucket: 'adhikar-2d604.appspot.com',
    iosBundleId: 'com.example.adhikar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6mPVHGA4ySjv2klvv9yKokd-GSTqsB3A',
    appId: '1:618958872225:ios:07d78f096b1c8c6977dae0',
    messagingSenderId: '618958872225',
    projectId: 'adhikar-2d604',
    storageBucket: 'adhikar-2d604.appspot.com',
    iosBundleId: 'com.example.adhikar.RunnerTests',
  );
}
